
sudo: required

language: node_js

services: docker

before_script:

script: platform=ios macaca run --verbose -d ./macaca-test/mobile-app-sample.test.js
after_script: 

after_failure: 

after_success: